package ru.roansa.trackeroo_telegram_publisher.api

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import okhttp3.MultipartBody
import okhttp3.OkHttpClient
import okhttp3.RequestBody.Companion.asRequestBody
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.HttpException
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import retrofit2.http.Multipart
import retrofit2.http.POST
import retrofit2.http.Part
import ru.roansa.trackeroo_core.logging.publish.ILogPublisher
import java.io.File

private const val BASE_API_URL = "https://api.telegram.org/"

private interface TelegramApiService {
    @Multipart
    @POST("/bot{botToken}/sendDocument")
    suspend fun uploadFile(
        @retrofit2.http.Path("botToken") botToken: String,
        @Part("chat_id") chatId: Long,
        @Part("caption") caption: String,
        @Part document: MultipartBody.Part
    )
}

/**
 * This class publish logs file to Telegram group/chat
 * @param botToken – token generated by BotFather bot in Telegram
 * @param chatId – id of chat where bot will be publish logs
 * @param caption – text that will be added to uploaded file in chat
 * @param isHttpLoggingEnabled – flag to enable HttpLoggingInterceptor logging. Strongly recommended using it only for local debug purposes
 */
class TelegramPublisher(
    private val botToken: String,
    private val chatId: Long,
    private val caption: String = "",
    private val isHttpLoggingEnabled: Boolean = false,
    val onResult: (PublishResult) -> Unit = {}
) : ILogPublisher<MultipartBody.Part>() {

    private val client = OkHttpClient.Builder().apply {
        if (isHttpLoggingEnabled) {
            addInterceptor(
                HttpLoggingInterceptor().apply { level = HttpLoggingInterceptor.Level.BODY }
            )
        }
    }.build()
    private val retrofit = Retrofit.Builder()
        .baseUrl(BASE_API_URL)
        .client(client)
        .addConverterFactory(GsonConverterFactory.create())
        .build()
    private val service = retrofit.create(TelegramApiService::class.java)
    private val scope = CoroutineScope(Dispatchers.Main)

    override fun publish(target: MultipartBody.Part) {
        scope.launch(context = Dispatchers.IO) {
            try {
                service.uploadFile(botToken, chatId, caption, target)
                onResult(PublishResult.Success("File uploaded"))
            } catch (e: Exception) {
                e.printStackTrace()
                val code = if (e is HttpException) e.code() else 0
                val message =
                    if (e is HttpException) e.response()?.errorBody()?.string() else e.message
                onResult(
                    PublishResult.Error(
                        code,
                        "TelegramPublisher occured an error while trying to publish logs: $message"
                    )
                )
            }
        }
    }

    override fun prepare(target: File): MultipartBody.Part {
        if (!target.isFile) {
            return MultipartBody.Part.createFormData("", "")
        }

        val requestFile = target.asRequestBody()
        return MultipartBody.Part.createFormData("document", target.name, requestFile)
    }

    sealed class PublishResult {
        data class Success(val message: String) : PublishResult()
        data class Error(val errorCode: Int, val errorMessage: String) : PublishResult()
    }
}